import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Turns data/*.json into TypeScript modules the engine imports.
 *
 * The JSON files stay the source of truth — card text is still never typed by
 * hand — but the engine cannot import them directly. Vercel transpiles each file
 * on its own and runs it as Node ESM, where a JSON import needs a type attribute,
 * and the transpiler drops that attribute on the way through. The result was a
 * function that crashed on load in production and worked everywhere else.
 *
 * A generated .ts module has none of those problems: it is just code. A test
 * checks it against the JSON, so the two cannot drift.
 *
 *   npm run gen:data
 */

const ROOT = process.cwd();
const OUT = join(ROOT, 'src', 'engine', 'generated');

const HEADER = `// Generated by scripts/gen-data.mjs from data/%s — do not edit by hand.
// Run \`npm run gen:data\` after changing the data file.
`;

function emit(file, jsonName, constName, type) {
  const data = JSON.parse(readFileSync(join(ROOT, 'data', jsonName), 'utf8'));
  const body = `${HEADER.replace('%s', jsonName)}
export const ${constName}${type} = ${JSON.stringify(data, null, 2)};
`;
  writeFileSync(join(OUT, file), body);
  return body.length;
}

mkdirSync(OUT, { recursive: true });
const a = emit('decklist.gen.ts', 'decklist.json', 'DECKLIST', '');
const b = emit('oracle-cards.gen.ts', 'oracle-cards.json', 'ORACLE_DATA', '');
console.log(`Wrote src/engine/generated/decklist.gen.ts (${a} bytes) and oracle-cards.gen.ts (${b} bytes).`);
